CVproject/Models/Competence.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace CVproject.Models
{
    public class Competence
    {
        [Key]
        public int Id { get; set; }
        [Display(Name = "Competence")]

        [Required(ErrorMessage = "Please enter a Competence.")]
        [StringLength(255)]
        public string Name { get; set; }

        public int CvId { get; set; }

        [ForeignKey(nameof(CvId))]
        public virtual CV Cv { get; set; }

        public Competence(int id)
        {
            CvId = id;
        }

        public Competence() { }
    }
}

CVproject/Controllers/CompetencesController.cs
using CVproject.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace CVproject.Controllers
{
    public class CompetencesController : Controller
    {
        private readonly CvContext _context;
        public CvViewModel cmv { get; set; }

        public CompetencesController(CvContext context) {
            _context = context;

           cmv = new CvViewModel
            {
                Competences = _context.Competences.ToList()
            };
        }


        public ActionResult _CompDetailsPartial()
        {
            return View(cmv);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult AddCompetence(Competence model)
        {
            
                _context.Competences.Add(model);
                _context.SaveChanges();
            

            return RedirectToAction("MyPage", "Persons");
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Delete(int id)
        {
            if (_context.Competences == null)
            {
                return Problem("Entity set 'CvContext.Competences'  is null.");
            }
            var comp = await _context.Competences.FindAsync(id);
            if (comp != null)
            {
                _context.Competences.Remove(comp);
                await _context.SaveChangesAsync();
            }

            return RedirectToAction("MyPage", "Persons");
        }


    }
}

CVproject/Views/Competences/Competence.cshtml
@model CVproject.Models.Competence

<form class="formgroup">
    <table class="form-table">
        <div class="competenceInstructions">
            <h5>Add Your Competences</h5>
            <h6>Use the "+" Button to Add More.</h6>
            <h6>Save When You're Done</h6>
        </div>
        <tr valign="top">

            <td id="container_height">
                <input class="registerTextBox" type="text" name="height[]" placeholder="" />
            </td>
            <td>
                <input class="addbtn" type="button" name="add" id="add" value="+">
            </td>
        </tr>
        <tr>
            <td>
            </td>
        </tr>

    </table>
    <input class="savebtn" type="submit" value="Add" />
</form>

CVproject/Views/Competences/_CompDetailsPartial.cshtml
@model CV

<h4>My Competences</h4>
    <div class="Competencesdiv d-flex flex-sm-wrap mb-2 mt-1">
        
        @if (Model.Competences != null)
        {

            @foreach (var competence in Model.Competences)
            {
            <div class="competencediv">
                <form asp-controller="Competences" asp-action="Delete" asp-route-id=@competence.Id method="post">
            
                <label class="lblcompetences">
                    @competence.Name
                      <input type="hidden" asp-for=@competence.Id/>
                        <button class ="btnDeleteCompetence" type="submit">
                            <span class="material-symbols-outlined msocomp">
                                close
                            </span>
                        </button>
                        
                        
                    
                </label>
            </form>
            </div>
                

            }

        }
    
    </div>

CVproject/Views/Competences/_CompetencePartial.cshtml
@model CVproject.Models.Competence

        @using (Html.BeginForm("AddCompetence", "Competences", FormMethod.Post))
        {


    <div class="formgroup">
        @Html.LabelFor(e => e.Name)<br />
        @Html.TextBoxFor(e => e.Name, new {@required  = "required" })
        <br />
    </div>
    <input type="hidden" asp-for=@Model.CvId />
    <input type="hidden" asp-for=@Model.Cv />


    <input class="savebtn" type="submit" value="Add" />
        }

CVproject/Views/Competences/_cvcomp.cshtml
@model CV

<h5>Competences</h5>
    <div class="Competencesdiv d-flex flex-sm-wrap mb-2 mt-1">
        
        @if (Model.Competences != null)
        {
        <ul>
            @foreach (var competence in Model.Competences)
            { <li>
            <div class="comp-cv-div">
                <label class="lblcompetences">@competence.Name </label>
                </div>
                </li>
            }
        </ul>
        }
        </div>