CVproject/Models/Experience.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Reflection;

namespace CVproject.Models
{
    public class Experience
    {
        [Key]
        public int Id { get; set; }

        [Required(ErrorMessage = "Please enter an Employer.")]
        [StringLength(255)]
        public string Employer { get; set; }

        [Required(ErrorMessage = "Please enter a Title.")]
        [StringLength(255)]
        public string Title { get; set; }

        [Required(ErrorMessage = "Please enter a start year.")]
        [Range(1950, 2023, ErrorMessage = "Please enter a start year")]
        [Display(Name = "Start Year")]
        public int StartYear { get; set; }

        [Required(ErrorMessage = "Please enter an end year.")]
        [Range(1950, 2023, ErrorMessage = "Please enter an end year")]
        [Display(Name = "End Year")]
        public int EndYear { get; set; }
        public int CvId { get; set; }

        [ForeignKey(nameof(CvId))]
        public virtual CV? Cv { get; set; }

        public Experience(int id)
        {
            CvId = id;
        }
        
        public Experience () { }
    }
}

CVproject/Controllers/ExperiencesController.cs
using CVproject.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace CVproject.Controllers
{
    public class ExperiencesController : Controller
    {
        private readonly CvContext _context;

        public ExperiencesController(CvContext ctx)
        {
            _context = ctx;
        }
        // GET: ExperiencesController
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult AddExperience(Experience model)
        {
            if (ModelState.IsValid)
            {
                if (model.EndYear < model.StartYear)
                {
                    TempData["errorMessageExp"] = "Please Make Sure End Year Is After Start Year";
                }
                else
                {
                    _context.Experiences.Add(model);
                    _context.SaveChanges();

                    TempData["errorMessageExp"] = "";
                }
            }
            else
            {
                TempData["errorMessageExp"] = "Please Complete All Fields Before Saving";
            }


            return RedirectToAction("MyPage", "Persons");
        }

        [HttpGet]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id)
        {
            Experience experience = _context.Experiences.Find(id);


            return PartialView("_ExpEdit", experience);
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> EditExperience([Bind("Id,Employer,Title,StartYear, EndYear,CvId")] Experience experience)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    _context.Experiences.Update(experience);
                    await _context.SaveChangesAsync();
                }
                catch
                {

                }
                return RedirectToAction("MyPage", "Persons");
            }
            return RedirectToAction("MyPage", "Persons");
        }


        // GET: EducationsController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Delete(int id)
        {

            if (_context.Experiences == null)
            {
                return Problem("Entity set 'CvContext.Experiences'  is null.");
            }

            var exp = await _context.Experiences.FindAsync(id);
            if (exp != null)
            {
                _context.Experiences.Remove(exp);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction("MyPage", "Persons");
        }

  

    }
}

CVproject/Views/Experiences/_ExpDetailsPartial.cshtml
@model CV
<div>
    
    <h4>My Experiences</h4>
    <div class="detaildiv">
    @foreach(var exp in Model.Experiences)
    {
            <div class="expDiv d-flex align-items-center">
        <div class="">
            <label class="lbledu">Employer: @exp.Employer</label> <br />
            <label class="lbledu">Title: @exp.Title</label> <br />
            <label class="lbledu">Period: @exp.StartYear - @exp.EndYear</label> <br />
        </div>

                <div class="editdelete d-flex">
                    <button type="button" class="btndelete edit-exp" data-toggle="modal"
                        data-target="#editexpmodal@(exp.Id)" id="btnedit" data-id="@exp.Id">
                        <span class="material-symbols-outlined msodelete">Edit</span>
                    </button>

                    <form asp-controller="Experiences" asp-action="Delete" asp-route-id=@exp.Id method="post">
                        <button class="btnDelete" type="submit" onclick="return confirm('Are You Sure You Want To Delete This?')">
                            <span class="material-symbols-outlined msodelete">delete</span>
                        </button>
                    </form>
                </div>
            </div>
            <div class="modal" id="editexpmodal@(exp.Id)" tabindex="-1" role="dialog">
                <div class="modal-dialog" role="document">
                    <div class="modal-content">
                        <div class="modal-header">
                            <h5 class="modal-title">@exp.Id</h5>
                            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                        </div>
                        @Html.Partial("~/Views/Experiences/_ExpEdit.cshtml", exp)
                    </div>
                </div>
            </div>
        
    }
        
    </div>

</div>

CVproject/Views/Experiences/_ExpEdit.cshtml
@model CVproject.Models.Experience

<div class="modal-body">
    @using (Html.BeginForm("EditExperience", "Experiences", FormMethod.Post))
    {
        <input type="hidden" asp-for=@Model.Id />
        <div class="form-group">
            @Html.LabelFor(e => e.Employer)<br />
            @Html.TextBoxFor(e => e.Employer, new { @class = "form-control" })<br />
        </div>

        <div class="form-group">
            @Html.LabelFor(e => e.Title)<br />
            @Html.TextBoxFor(e => e.Title, new { @class = "form-control" })<br />
        </div>
        
    <div class="form-group">
    @Html.LabelFor(e => e.StartYear)<br />
    @Html.DropDownListFor(e => e.StartYear,
    new SelectList(Enumerable.Range(1950, 74).Reverse()), Model.StartYear.ToString()
    ,
    new { @class = "form-control" }) <br />

    </div>

    <div class="form-group">
    @Html.LabelFor(e => e.EndYear)<br />
    @Html.DropDownListFor(e => e.EndYear,
    new SelectList(Enumerable.Range(1950, 74).Reverse()),Model.EndYear.ToString(),
    new { @class = "form-control" })
    </div>
        <input type="hidden" asp-for=@Model.CvId />
        <input type="hidden" asp-for=@Model.Cv />

        <div class="modal-footer">
            <button type="submit" class="btn btn-primary">Save changes</button>
            <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        </div>
    }

</div>

CVproject/Views/Experiences/_ExperiencePartial.cshtml
@model CVproject.Models.Experience

@using (Html.BeginForm("AddExperience", "Experiences", FormMethod.Post))
{
    <p class="text-danger m-2">@TempData["errorMessageExp"]</p>

    <div class="formgroup">
        @Html.LabelFor(e => e.Employer)<br />
        @Html.TextBoxFor(e => e.Employer, new {@required  = "required" })
        <br />
    </div>

    <div class="formgroup">
        @Html.LabelFor(e => e.Title)<br />
        @Html.TextBoxFor(e => e.Title, new {@required  = "required" })
        <br />
    </div>


    <div class="formgroup div-year">
        <label asp-for="StartYear" class="col-md-2 control-label"></label>
        <div class="col-md-5">
            @Html.DropDownListFor(e => e.StartYear,
        new SelectList(Enumerable.Range(1950, 74).Reverse()),
        "-- Select Start Year ---",
        new { @class = "form-control", @required  = "required" })
        </div>        <br />

       <label asp-for="EndYear" class="col-md-2 control-label"></label>
        <div class="col-md-5">
            @Html.DropDownListFor(e => e.EndYear,
        new SelectList(Enumerable.Range(1950, 74).Reverse()),
        "-- Select End Year ---",
        new { @class = "form-control", @required  = "required" })
        </div>        <br />

    </div>
    <input type="hidden" asp-for=@Model.CvId />
    <input class="savebtn btnexp" type="submit" value="Add" />
}

CVproject/Views/Experiences/_cvexp.cshtml
@model CV
<div class="cvexppartdiv">
    <div class="title">
    <h4>Experiences</h4>
    </div>
    <div class="detaildiv">
        @foreach (var exp in Model.Experiences)
        {
            <div class="expDiv d-flex align-items-center">
                <div class="cvexpdiv">
                    <label class="lbledu">Employer: @exp.Employer</label> <br />
                    <label class="lbledu">Title: @exp.Title</label> <br />
                    <label class="lbledu">Period: @exp.StartYear - @exp.EndYear</label> <br />
                </div>
                </div>
        }
        
        </div>
 </div>