CVproject/Models/Message.cs
using System.ComponentModel.DataAnnotations.Schema;
using System.Xml.Serialization;

namespace CVproject.Models
{
    public class Message
    {
        public int Id { get; set; }
        public string SenderName { get; set; }
        public string ReceiverId { get; set; }
        public string Heading { get; set; }
        public string Text { get; set; }

        public bool IsRead { get; set; } = false;

        [XmlIgnore]
        [ForeignKey(nameof(ReceiverId))]
        public virtual Person? Receiver { get; set; }

    }
}

CVproject/ViewModels/MessageViewModel.cs
using CVproject.Models;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace CVproject.ViewModels
{
    public class MessageViewModel
    {
        [Required(ErrorMessage = "Please enter a sender name.")]
        [StringLength(255)]
        public string SenderName { get; set; }

        [Required(ErrorMessage = "Please enter a receiver name.")]
        [StringLength(255)]
        public string ReceiverName { get; set; }

        [Required(ErrorMessage = "Please enter receiver id.")]
        [StringLength(255)]
        public string ReceiverId { get; set; }

        [Required(ErrorMessage = "Please enter a heading.")]
        [StringLength(255)]
        public string Heading { get; set; }

        [Required(ErrorMessage = "Please enter a text.")]
        [StringLength(255)]
        public string Text { get; set; }


    }
}

CVproject/Controllers/MessagesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using CVproject.Models;
using System.Text.Json;
using Microsoft.AspNetCore.Identity;
using System.Security.Claims;
using CVproject.ViewModels;
using Microsoft.Extensions.Options;

namespace CVproject.Controllers
{
    public class MessagesController : Controller
    {
        private readonly CvContext _context;

        private HttpClient _httpClient;

        private readonly UserManager<Person> _userManager;

        public MessagesController(CvContext context, HttpClient httpClient, UserManager<Person> userManager)
        {
            _context = context;
            _httpClient = httpClient;
            _userManager = userManager; 
        }

        //GET: Messages from API
        public async Task<IActionResult> Index()
        {
            var userId = User.FindFirst(ClaimTypes.NameIdentifier).Value;

            try { 
                HttpResponseMessage response = await _httpClient.GetAsync($"message/{userId}" );
                string data = await response.Content.ReadAsStringAsync();
                var opstions = new JsonSerializerOptions
                {
                    PropertyNameCaseInsensitive = true,
                };
                List<Message> messageList = JsonSerializer.Deserialize<List<Message>>(data, opstions).ToList();

                return View(messageList);
            }
            catch( Exception e)
            {
                Console.WriteLine("Caught exaption", e);
            }

            ModelState.AddModelError(",", "Can't get messages");
            return View();
        }


        //Update message , set IsRead to true
        // GET: Messages/Details/5 API
        public async Task<IActionResult> Details(int? id)
        {
            //Get message from API
            try
            {
                HttpResponseMessage response = await _httpClient.GetAsync($"message/detail/{id}");
                string data = await response.Content.ReadAsStringAsync();
                var opstions = new JsonSerializerOptions
                {
                    PropertyNameCaseInsensitive = true,
                };
                Message message = JsonSerializer.Deserialize<Message>(data, opstions);


                if (message.IsRead == false)
                {
                    //To save update
                    message.IsRead = true;

                    string messageData = JsonSerializer.Serialize(message);
                    var jsonData = new StringContent(messageData, System.Text.Encoding.UTF8, "application/json");

                    //Save via the Put method in API
                    HttpResponseMessage responseMessage = await _httpClient.PutAsync($"message/{message.Id}", jsonData);
                }

                return View(message);
            }
            catch (Exception e)
            {
                Console.WriteLine("Caught exaption", e);
            }
            ModelState.AddModelError(",", "Can't update message to Read");
            return View();
        }

       

        // GET: Messages/Create
        public IActionResult Create(string? id)
        {
            var user = _userManager.GetUserAsync(HttpContext.User).Result;

            var model = new MessageViewModel();

            if(user != null) 
            {
                model.SenderName = user.Name;
               
            }
            model.ReceiverName = _context.Users.Find(id).Name; 
            model.ReceiverId = id;
            return View(model);
        }

        // POST: Messages/Create API
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create( MessageViewModel messageViewModel ) 
        {
            try
            {
                var message = new Message();
                message.SenderName = messageViewModel.SenderName;
                message.ReceiverId = messageViewModel.ReceiverId;
                message.Heading = messageViewModel.Heading;
                message.Text = messageViewModel.Text;


                if (ModelState.IsValid)
                {
                    var options = new JsonSerializerOptions
                    {
                        PropertyNameCaseInsensitive = true,
                    };

                    string data = JsonSerializer.Serialize(message, options);
                    var contentData = new StringContent(data, System.Text.Encoding.UTF8, "application/json");

                    HttpResponseMessage response = await _httpClient.PostAsync($"message", contentData);
                    TempData["message"] = "Message was sent";
                    ViewBag.Message = "Message was sent";
                    return RedirectToAction("Create");
                }
                return View(messageViewModel);
            }
            catch (Exception e)
            {
                Console.WriteLine("Caught exaption", e);
            }
            ModelState.AddModelError(",", "Can't send message");
            return View();
        }
     

        // GET: Messages/Delete/5 API
        public async Task<IActionResult> Delete(int? id)
        {
            try
            {
                HttpResponseMessage response = await _httpClient.GetAsync($"message/detail/{id}");
                string data = await response.Content.ReadAsStringAsync();
                var opstions = new JsonSerializerOptions
                {
                    PropertyNameCaseInsensitive = true,
                };
                Message message = JsonSerializer.Deserialize<Message>(data, opstions);

                return View(message);
            }
            catch (Exception e)
            {
                Console.WriteLine("Caught exaption", e);
            }
            ModelState.AddModelError(",", "Can't delete message");
            return View();
        }


        // POST: Messages/Delete/5 API
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int? id)
        {
            //Get messaeg from API
            try
            {
                HttpResponseMessage messageResponse = await _httpClient.DeleteAsync($"message/{id}");

                return RedirectToAction(nameof(Index));
            }
            catch (Exception e)
            {
                Console.WriteLine("Caught exaption", e);
            }
            ModelState.AddModelError(",", "Can't delete message");
            return View();
        }

        private bool MessageExists(string id)
        {
            return _context.Messages.Any(e => e.ReceiverId.Equals(id));
        }


       
    }
}

CVproject/Controllers/PersonsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using CVproject.Models;
using Microsoft.AspNetCore.Identity;
using CVproject.ViewModels;
using System.Security.Claims;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Microsoft.IdentityModel.Tokens;
using Microsoft.Build.ObjectModelRemoting;
using Castle.Core.Resource;
using Newtonsoft.Json;

namespace CVproject.Controllers
{
    public class PersonsController : Controller
    {
        private readonly CvContext _context;

        private readonly UserManager<Person> _userManager;

        private readonly IWebHostEnvironment _webHostEnvironment;

        public List<Person> searchList;

        public PersonsController(CvContext context, UserManager<Person> userManager)
        {
            _context = context;
            _userManager = userManager;
            searchList = new List<Person>();
        }

      

        // GET: Persons

        [HttpGet]
        public async Task<IActionResult> Index(string searchString1, string searchString2)
        {
            List<Person> personListAll = _context.Users.Include(p => p.CV).ThenInclude(c => c.Competences).ToList();
            List<Person> personsListPrivate = _context.Users.Include(p => p.CV).ThenInclude(c => c.Competences).Where(p => !p.IsPrivate).ToList();

            var searches = new List<string>();
            if (!String.IsNullOrEmpty(searchString1))
            {
                searches.Add("\"" + searchString1 + "\" ");
            }
            if (!String.IsNullOrEmpty(searchString2))
            {
                searches.Add("\"" + searchString2 + "\"");
            }
                

            ViewBag.Searches = searches;

            // Both strings are null or empty
            if (String.IsNullOrEmpty(searchString1) && String.IsNullOrEmpty(searchString2))
            {
                PersonSearchViewModel viewmodel = new PersonSearchViewModel
                {
                    persons = personListAll
                };
                if (!User.Identity.IsAuthenticated)
                {
                    viewmodel.persons = personsListPrivate;
                }

                return View(viewmodel);
            }

            // String2 is null or empty
            if (!String.IsNullOrEmpty(searchString1) && String.IsNullOrEmpty(searchString2))
            {
                PersonSearchViewModel viewmodel = new PersonSearchViewModel
                {
                    persons = personListAll.Where(u => u.Name.IndexOf(searchString1, StringComparison.OrdinalIgnoreCase) >= 0).ToList()

                };

                if (!User.Identity.IsAuthenticated)
                {
                    viewmodel.persons = personsListPrivate.Where(u => u.Name.IndexOf(searchString1, StringComparison.OrdinalIgnoreCase) >= 0).ToList();
                }
                return View(viewmodel);
            }


            //None are null or empty
            if (!String.IsNullOrEmpty(searchString1) && !String.IsNullOrEmpty(searchString2))
            {

                PersonSearchViewModel viewmodel = new PersonSearchViewModel
                {
                    persons = personListAll.Where(u => u.Name.IndexOf(searchString1, StringComparison.OrdinalIgnoreCase) >= 0)
                        .Where(u => u.CV.Competences.Any(c => c.Name.IndexOf(searchString2, StringComparison.OrdinalIgnoreCase) >= 0)).ToList()
                };
                if (!User.Identity.IsAuthenticated)
                {
                    viewmodel.persons = personsListPrivate.Where(u => u.Name.IndexOf(searchString1, StringComparison.OrdinalIgnoreCase) >= 0)
                        .Where(u => u.CV.Competences.Any(c => c.Name.IndexOf(searchString2, StringComparison.OrdinalIgnoreCase) >= 0)).ToList();
                }
                return View(viewmodel);
            }


            // String1 is null or empty
            if (String.IsNullOrEmpty(searchString1) && !String.IsNullOrEmpty(searchString2))
            {
                PersonSearchViewModel viewmodel = new PersonSearchViewModel
                {
                    persons = personListAll.Where(u => u.CV.Competences.Any(c => c.Name.IndexOf(searchString2, StringComparison.OrdinalIgnoreCase) >= 0)).ToList()
                        
                };
                if (!User.Identity.IsAuthenticated)
                {
                    viewmodel.persons = personsListPrivate.Where(u => u.CV.Competences.Any(c => c.Name.IndexOf(searchString2, StringComparison.OrdinalIgnoreCase) >= 0)).ToList();
                }
                return View(viewmodel);
            }
            return View(personListAll);

        }


  
      

        private bool PersonExists(string id)
        {
          return _context.Users.Any(e => e.Id.Equals( id));
        }

        public IActionResult ChangePassword()
        {
            return View();  
        }

        [HttpGet]
        public IActionResult MyPage()
        {
            var user = _userManager.GetUserAsync(HttpContext.User).Result;
            var _cv = _context.Cvs.Where(c => c.Id.Equals(user.CvId)).FirstOrDefault();

            var nrOfViews = CVsController.GetNumberOfViewsAsync(_cv.Id).Result;
            ViewBag.NrOfViews = nrOfViews;

            var viewmodel = new CvPersonViewModel
            {
                person = user,
                cv = _cv
            };

            

            var memberList = _context.ProjectMembers.ToList();
            var projectList = _context.Project.ToList();
            var userList = _context.Users.ToList();

            var projectsOfActiveUsers = from p in projectList
                                        join u in userList on p.ProjectOwner equals u.Id
                                        where u.IsActive == true
                                        select p;

            var proj = from p in projectsOfActiveUsers
                       join m in memberList on p.Id equals m.ProjectId
                       join u in userList on m.PersonId equals u.Id
                       where u.Id == user.Id
                       select p;

            ViewBag.Projects = proj;


            var owner = _context.Project.Where(p => p.ProjectOwner.Equals(user.Id));
            ViewBag.ProjectsOwner = owner;


            return View(viewmodel);
        }

        [HttpPost]
        public IActionResult MyPage(Person person)
        {
            var user = _userManager.GetUserAsync(HttpContext.User).Result;
            user.Name = person.Name;
            user.Email = person.Email;
            user.Github = person.Github;
            user.IsPrivate = person.IsPrivate;


            //Code to Upload image
            try { 

                byte[] bytes = null; 

                if (person.ImageFile != null)
                {
    

                    using (Stream fileStream = person.ImageFile.OpenReadStream())
                    {
                        using (BinaryReader binaryReader = new BinaryReader(fileStream))
                        {
                            bytes = binaryReader.ReadBytes((Int32)fileStream.Length);
                        }
                    }

                    user.Picture = Convert.ToBase64String(bytes, 0, bytes.Length);
                }
            }
            catch (Exception e)
            {
                Console.WriteLine("Caught exaption", e);
            }

            var memberList = _context.ProjectMembers.ToList();
            var projectList = _context.Project.ToList();
            var userList = _context.Users.ToList();

            var projectsOfActiveUsers = from p in projectList
                                        join u in userList on p.ProjectOwner equals u.Id
                                        where u.IsActive == true
                                        select p;

            var proj = from p in projectsOfActiveUsers
                       join m in memberList on p.Id equals m.ProjectId
                       join u in userList on m.PersonId equals u.Id
                       where u.Id == user.Id
                       select p;

            ViewBag.Projects = proj;
            var owner = _context.Project.Where(p => p.ProjectOwner.Equals(user.Id));

            ViewBag.ProjectsOwner = owner;



            if (ModelState.IsValid)
            {
                _context.Users.Update(user);
                _context.SaveChanges();
                var current_User = _userManager.GetUserAsync(HttpContext.User).Result;

                var _cv = _context.Cvs.Where(c => c.Id.Equals(current_User.CvId)).FirstOrDefault();

                var viewmodel = new CvPersonViewModel
                {
                    person = current_User,
                    cv = _cv

                };

                return View(viewmodel);
            }

            var model = new CvPersonViewModel
            {
                person = person,
                cv = _context.Cvs.Where(c => c.Id.Equals(user.CvId)).FirstOrDefault()
            };

            return View(model);
        }


    }
}

CVproject/Views/Messages/Create.cshtml
@model CVproject.ViewModels.MessageViewModel

@{
    ViewData["Title"] = "Create";
}


<form asp-action="Create">
    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
    @if (Model != null && Model.SenderName != null)
    {
        
        <label asp-for="SenderName" class="control-label">From: @Model.SenderName</label>
        <input type="hidden" asp-for="SenderName" />
        
    }
    else
    {
    <div class="form-group">
        <label asp-for="SenderName" class="control-label">From:</label>
        <input asp-for="SenderName" class="form-control" />
        <span asp-validation-for="SenderName" class="text-danger"></span>
    </div>
    }
    <label class="control-label">To: @Model.ReceiverName</label>
    <input type="hidden" asp-for="ReceiverName" />
    <div class="form-group">
        <label asp-for="Heading" class="control-label"></label>
        <input asp-for="Heading" class="form-control" />
        <span asp-validation-for="Heading" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="Text" class="control-label"></label>
        <input asp-for="Text" class="form-control" />
        <span asp-validation-for="Text" class="text-danger"></span>
    </div>
    <input type="hidden" asp-for="ReceiverId" />
  
    <div class="form-group">
        <input type="submit" value="Send" class="btn btn-primary" />
    </div>
    @if(TempData != null)
    {
        <p>@TempData["message"]</p>
    }
</form>

<div>
    <a asp-controller="Persons" asp-action="Index">Back to List</a>
</div>

CVproject/Views/Messages/Delete.cshtml
@model CVproject.Models.Message

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Message</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Text)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Text)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="SenderName" />
        <input type="hidden" asp-for="ReceiverId" />
        <input asp-action="DeleteConfirmed" asp-route-id="@Model?.Id" type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
   
</div>

CVproject/Views/Messages/Details.cshtml
@model CVproject.Models.Message

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Message</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Heading)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Heading)
        </dd>
    </dl>
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Text)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Text)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Index">Back to List</a>
</div>

CVproject/Views/Messages/Edit.cshtml
@model CVproject.Models.Message

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Message</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="SenderName" />
            <input type="hidden" asp-for="ReceiverId" />
            <div class="form-group">
                <label asp-for="Text" class="control-label"></label>
                <input asp-for="Text" class="form-control" />
                <span asp-validation-for="Text" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

CVproject/Views/Messages/Index.cshtml
@model IEnumerable<CVproject.Models.Message>

@{
    ViewData["Title"] = "Messages";
}

<h1>Messages</h1>

<p>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Heading)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Heading)
            </td>
            <td>
                @Html.ActionLink("Details", "Details", new { id=item.Id }) |
                    @Html.ActionLink("Delete", "Delete", new { id=item.Id })
            </td>
            @if(item.IsRead)
            {
                 <td>
                    <p>Read</p>
                 </td>
            }
        </tr>
}
    </tbody>
</table>